### ISSUE TITLE
Urgent property is not working

### ISSUE THREAD

**Issue by getzze** [Elv13/tyrannical#38]
Without tyrannical, when a client that is not focused receives a urgent bell, its tag becomes highlighted normally.
But when using tyrannical, the clients are not responding to the urgent bell signal anymore. Awful is managing a list of clients that received a urgent bell, but this list remains empty when tyrannical is loaded. I tried to reconnect the signal `property::urgent` to the clients without success.

I am using awesome 3.5.5

**Comment by Elv13** [comment]
The patch has been merged years ago and will be released along with Awesome 4.0 in a couple of weeks. I forgot to update this issue sooner.
