### ISSUE TITLE
fancy prompt from the FAQ doesn't work

### ISSUE THREAD

**Issue by pazz** [Elv13/tyrannical#50]
Hi!

I tried to replace

```
awful.key({ modkey },            "r",     function () mypromptbox[mouse.screen]:run() end),
```

with your fancy code suggested in the README.
Its not working, not even in the example.rc.lua.

I'm on awesome 3.5.6 (stable) from tarball, just ompiled.
Any ideas?

**Comment by Elv13** [comment]
Sorry, the patch wasn't merged upstream, I was too busy/lazy to get this done in time...

**Comment by Elv13** [comment]
It works now, but only in Awesome 4.0+. It was rejected from 3.5 for being too scary for a point release.
