### ISSUE TITLE
Undesired behaviour with predefined shortcuts

### ISSUE THREAD

**Issue by ghost** [Elv13/tyrannical#55]
Hello,

recently I noticed that there are the predefined shortcuts in shortcuts.lua and started using them. In my rc.conf I have an tyrannical rule to add all terminals to one tag:

``` lua
tyrannical.tags = {
    {
        name        = "term",
        init        = true, 
        exclusive   = true,
        class       = { "xterm", "urxvt", "URxvt", "XTerm" }
    },
...
```

Now I tried using the `term_in_current_tag()` and `new_tag_with_term()` functions. Unfortunately all terms will be moved to the "term" tag. I tried to prevent this behaviour in the `term_in_current_tag()` function with following statement:

``` lua
local function term_in_current_tag()
    local s = capi.client.focus and capi.client.focus.screen or capi.mouse.screen
    local t = aw_tag.selected(s)
    if not t then return end
    aw_util.spawn(terminal,{intrusive=true,slave=true,tag=t})
end
```

But it doesn't working. Can you help here?

Thank you!

**Comment by Elv13** [comment]
Wow, I missed that one, sorry. In case you still care and don't hate me for it, only urxvt compiled with startup notification support, gnome-terminal or other libvte based tems and the KDE4 version of Konsole correctly support this.
