### ISSUE TITLE
Can't add class with a hyphen in the name to a tyrannical.properties. array

### ISSUE THREAD

**Issue by ViktorNova** [Elv13/tyrannical#57]
This throws an error:
````
tyrannical.properties.border_width  = {
    lxqt-panel =   0
}
````
but this works perfectly:
````
tyrannical.properties.border_width  = {
    XTerm =   0
}
````

"lxqt-panel" works just fine in other parts of Tyrannical where it's in quotations, but in these sections quotations don't work. I have also tried escaping it with % and %% with no luck

**Comment by freehaha** [comment]
Hi,
could you try this to see if it works?
```lua
tyrannical.properties.border_width  = {
    ["lxqt-panel"] =   0
}
```

**Comment by ViktorNova** [comment]
this works! thank you =)
