### ISSUE TITLE
exec_once exec'ing more than once

### ISSUE THREAD

**Issue by smcgrath** [Elv13/tyrannical#62]
I imagine this could easily be user error, but I've got just a slightly edited version of the included example config. I've added an exec_once {"google-chrome-stable"} to my 'Internet' tag.

Visiting the tag for the first time works as expected, spawning a Chrome instance. However, switching away and back to the Internet tag spawns another instance.

Is there an issue here, or am I doing something stupid? Config attached.
[rc.lua.txt](https://github.com/Elv13/tyrannical/files/160656/rc.lua.txt)

**Comment by smcgrath** [comment]
Aah, I think I might have already figured this out from the code. Chrome needs to be launched with the command 'google-chrome-stable', but the exec_once functionality is checking to see if it's running with ps, where the chrome process is simply called 'chrome'.

I'll just add a symlink in my ~/bin and life should be good.

**Comment by Elv13** [comment]
Some applications are not correctly detected. This happen when the executable name (`google-chrome-stable`) is not the same as the process name `/opt/google/chrome/chrome`.

A quick fix for this is to create an executable symlink in /usr/bin that match the exec-once script

```lua
awful.util.spawn_with_shell("ps -ef | grep -v grep | grep '" .. v .. "' > /dev/null || (" .. v .. ")")
```

It is like the startup notification extension. If the app misbehave, there is not much thing to do.

**Comment by smcgrath** [comment]
Yep, that took care of it for me, thanks.

**Comment by ff2000** [comment]
> It is like the startup notification extension. If the app misbehave, there is not much thing to do.

One could add an optional argument that specifies the process name to track.
Also tyrannical could track known misbehaving applications itself.

But I did not look at the source code if that's really possible...

**Comment by Elv13** [comment]
Tyrannical isn't really "smart" (on purpose).

It is designed as a thin wrapper around `awful.tag` to get as many `shifty` features as I could without adding "real" logic. The project is currently "complete" for Awesome 3.5. When 3.6 will be released, I will push a new version. The `exec_once` hack will be removed and will instead use an extended version of startup-notification tracking. It will solve this bug, but there is a lot of misbehaving SN-ID implementations, so some other clients will break.

I pushed an early version of SN-id in Awesome 3.5.3, but the 3.6 API will be better suited for this type of features.
