### ISSUE TITLE
matches in a tag

### ISSUE THREAD

**Issue by arkhan** [Elv13/tyrannical#67]
you can send all matches (as xfce) to a tag ...?

**Comment by Elv13** [comment]
Please better define what you want. In "matches" do you talk about string RegEx like matching of the title? If yes, then please use an `awful.rule` to set the `overwrite_class` property. See the FAQ section of the readme for this.

Tyrannical doesn't do its own matching. It is out of the project scope. It is why matching is delegated to `awful.rules`. The same goes for tag re-ordering. Tyrannical try to address 80% of the "value" provided by tag based declarative rules. Everything else is considered scope creep.

**Comment by arkhan** [comment]
for example, that all applications starting with xfce- * go to a specified label.

**Comment by Elv13** [comment]
Closing as my previous answer stands. Use `awful.rules` for this.
