### ISSUE TITLE
Tag spesific wallpapers

### ISSUE THREAD

**Issue by SenpaiDev** [Elv13/tyrannical#68]
How can i have a wallpaper predefined for a spesific tag?

**Comment by Elv13** [comment]
Hello,

Not related to Tyrannical, but something like

Awesome 3.5 (untested):

```lua
capi.tag.connect_signal("property::selected", function(t) if not t.selected then return end; gears.wallpaper.maximized(awful.tag.getproperty(t, "wallpaper"), awful.tag.getscreen(t), true) end)
capi.tag.connect_signal("property::wallpaper", function(t)  if not t.selected then return end; gears.wallpaper.maximized(awful.tag.getproperty(t, "wallpaper"), awful.tag.getscreen(t), true) end)
```

Awesome 3.6 (also untested):

```lua
for _, prop in ipairs {"selected", "wallpaper"} do
   capi.tag.connect_signal("property::"..prop, function(t) 
       if not t.selected then return end
       gears.wallpaper.maximized(t.wallpaper, t.screen, true)
   end)
end

```

Now, if you set a wallpaper to a tag (`awful.tag.setproperty(t, "wallpaper", "/path")` for 3.5 and `t.wallpaper = "/path"` for 3.6, or in the tyrannical tag definition, or `awful.rules`), then it should do about what you want. Again, this is untested.

**Comment by Elv13** [comment]
Closing as it isn't within Tyrannical scope.
