### ISSUE TITLE
tyrannical won't remember floating client size and position

### ISSUE THREAD

**Issue by basaran** [Elv13/tyrannical#87]
To reproduce:

```
tyrannical.properties.floating = {
   "Termite" , "Xterm", "Galculator"
}
tyrannical.properties.ontop = {
    "Termite", "Xterm",  "Galculator"
}
```
> Launch Xterm or Termite or Galculator, change window size, position and close.
They will start from top-left corner.
> Reopen Xterm or Termite or Galculator, and they will start from the top-left corner.

Use case: Use ranger as a floating file browser.

Notes:
Galculator is a GTK client. 
Other classes, such as "Notepadqq", "Emacs", "Nemo" are fine. All locations, sizes and ontop properties are kept. Ontop properties are fine for Termite, Xterm, Galculator as well.

**Comment by Elv13** [comment]
Floating size and position are provided by the client, not Awesome/Tyrannical. Storing this information is not within the scope of tyrannical, but could be implemented as another module using the Awesome v4.3+ `awful.rules.add_rule_source` API.
